server: 
  port: 56083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:56080/eureka/


#  cloud:
#   alibaba:
#      seata:
#        tx-service-group: seata-demo-bank1-fescar-service-group

logging:
  level:
    root: INFO
    io:
      seata: INFO
    org:
      springframework:
        cloud:
          alibaba:
            seata:
              web: INFO


